server:
  port: 8300

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启SpringCloud Gateway的注册中心发现配置
      routes:
        - id: api-admin-route
          uri: http://localhost:8100
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: api-order-route
          uri: http://localhost:8200
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1


eureka:
  instance:
    instance-id:  ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ #Eureka地址


