server:
  port: 8100

spring:
  application:
    name: admin
  datasource:
    url: jdbc:mysql://localhost:3306/pro?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    instance-id:  ${spring.application.name}
  client:
    fetch-registry: true #要不要去注册中心获取其他服务的地址
    register-with-eureka: true #自己就是注册中心，不用注册自己
    service-url:
      defaultZone: http://localhost:8000/eureka/ #Eureka地址

mybatis-plus:
  mapper-locations:  classpath*:/mapper/*/*.xml
#  mapper-locations: classpath*:/mapper/*/*.xml
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



